//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.13 at 03:22:53 PM IST 
//

package io.mosip.kernel.biometrics.entities;

import lombok.Data;

import javax.xml.bind.annotation.*;

@Data
@XmlRegistry
public class ObjectFactory {
    public ObjectFactory() {}

    public BIR createBIR() {
        return new BIR();
    }
    // Add other factory methods as needed
}