//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.13 at 03:22:53 PM IST 
//

package io.mosip.kernel.biometrics.entities;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Represents a registry identifier consisting of an organization and type.
 *
 * This class defines a unique identifier used within a registry system. It
 * comprises two components: - organization: The organization or entity that
 * owns or defines the format/standard being identified. - type: The specific
 * type or identifier within the organization's domain (e.g., fingerprint format
 * version).
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistryIDType", propOrder = { "organization", "type" })
@Data
@AllArgsConstructor
@NoArgsConstructor
public class RegistryIDType implements Serializable {
	/**
	 * The organization or entity that owns or defines the format/standard being
	 * identified.
	 */
	@XmlElement(name = "Organization", required = true)
	protected String organization;

	/**
	 * The specific type or identifier within the organization's domain (e.g.,
	 * fingerprint format version).
	 */
	@XmlElement(name = "Type", required = true)
	protected String type;
}