//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.13 at 03:22:53 PM IST 
//

package io.mosip.kernel.biometrics.constant;

/**
 * Enumerates the different processing levels of biometric data.
 *
 * This JAXB-generated enum represents the "ProcessedLevelType" element found in an XML schema. It defines the
 * various stages of processing that a biometric sample may undergo within a biometric system, such as raw,
 * intermediate, and processed.
 *
 */

import java.io.Serializable;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "ProcessedLevelType")
@XmlEnum
public enum ProcessedLevelType implements Serializable {
	/**
	 * Raw: Unprocessed biometric data in its original captured format (e.g., sensor
	 * image).
	 */
	@XmlEnumValue("Raw")
	RAW("Raw"),

	/**
	 * Intermediate: Biometric data that has undergone some initial processing
	 * (e.g., feature extraction). This level may represent data after basic
	 * transformations or noise reduction.
	 */
	@XmlEnumValue("Intermediate")
	INTERMEDIATE("Intermediate"),

	/**
	 * Processed: Biometric data that is ready for use in biometric operations
	 * (e.g., matching, verification). This level typically represents data after
	 * all necessary processing steps are complete.
	 */
	@XmlEnumValue("Processed")
	PROCESSED("Processed");

	private final String value;

	ProcessedLevelType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static ProcessedLevelType fromValue(String v) {
		for (ProcessedLevelType c : ProcessedLevelType.values()) {
			if (c.value.equalsIgnoreCase(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}
}