//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.13 at 03:22:53 PM IST 
//

package io.mosip.kernel.biometrics.constant;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import io.mosip.kernel.biometrics.entities.RegistryIDType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents quality information associated with a biometric sample.
 *
 * This class is generated by JAXB (Java Architecture for XML Binding) and
 * represents the "QualityType" element found in an XML schema. It contains
 * details about the algorithm used to assess quality, the calculated score
 * (unsigned integer), and an optional flag indicating a quality calculation
 * failure.
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QualityType", propOrder = { "algorithm", "score", "qualityCalculationFailed" })
@Data
@NoArgsConstructor
@AllArgsConstructor
public class QualityType implements Serializable {
	/**
	 * The algorithm used to calculate the quality score (e.g., fingerprint minutiae
	 * quality).
	 *
	 * This element is represented by the {@link RegistryIDType} enum and specifies
	 * the type of quality assessment algorithm applied.
	 */
	@XmlElement(name = "Algorithm", required = true)
	protected RegistryIDType algorithm;

	/**
	 * The calculated quality score of the biometric sample.
	 *
	 * This field represents the quality score as an unsigned integer (`Long`).
	 * Higher scores generally indicate better quality.
	 */
	@XmlElement(name = "Score")
	@XmlSchemaType(name = "unsignedInt")
	protected Long score;

	/**
	 * Flag indicating a failure during quality calculation (optional).
	 *
	 * This element is a string and can be used to provide details about any issues
	 * encountered while calculating the quality score.
	 */
	@XmlElement(name = "QualityCalculationFailed")
	protected String qualityCalculationFailed;
}